apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-provider
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-provider
  template:
    metadata:
      labels:
        app: payment-provider
    spec:
      containers:
      - name: payment-provider
        image: payment-provider:latest
        imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 999
        runAsNonRoot: true
