apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-provider
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payment-provider
  template:
    metadata:
      labels:
        app: payment-provider
    spec:
      containers:
      - name: payment-provider
        ports:
          - containerPort: 8082
        image: payment-provider:latest
        imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 999
        runAsNonRoot: true

---
kind: Service
apiVersion: v1
metadata:
  name: payment-provider
spec:
  type: ClusterIP
  selector:
    app: payment-provider
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082